# Qué es y cómo se utiliza Numpy

Datos importantes:

- **Numpy** es una librería muy importante para el ecosistema de Python ya que es la base de todos los cálculos científicos y muchas de las librerías de Machine Learning.

- **Scikit-Learn** con sus modelos, cuando retorna un resultado, en general lo retorna en un formato Numpy.

- La API de Numpy tiene muchas similitudes con Pandas.

- Numpy reemplaza de forma más eficiente lo que podría ser un tipo lista. En las listas podemos tener conjuntos de elementos numéricos. Sin embargo las listas no logran manejar datos de dos dimensiones.

- Las listas no poseen métodos que son prácticos para hacer aritmética.

- Es importante saber que otros lenguajes de programación poseen librerías altamente optimizadas para hacer cálculos numéricos con vectores de datos. Numpy es esa librería para el lenguaje de programación de Python.
np.

- linspace es una función que permite crear un array de una dimensión de números entre 0 y 1.
Los array a diferencia de otros objetos en Python están fuertemente tipificados. Esta tipificación fuerte es necesaria porque es una de las cosas que permite que esta librería sea más rápida que ocupar listas, por ejemplo.

## Arrays

In [15]:
#import la libreria
import numpy as np

In [16]:
a1 = np.array([1,2,3])
type(a1)

numpy.ndarray

In [17]:
a2 = np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a3 = np.zeros((2,3))
a3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
a4 = np.ones((2,3))
a4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
from IPython.display import display
display(a3);display(a4)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a5 = np.linspace(0,1,10)
#Distancias de forma regular. (b-a)(n-1)
display(a5)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Dimensión de un array